### ISSUE TITLE
Error at the step Import Demo Data

### ISSUE THREAD

**Issue by fitprotracker** [saasacademy/saas-template-wp#2]
hey team.  I have tried installing the Authority site in Wordpress and getting a constant error when Importing Demo Data.

I tried 3 different areas and hit the same error on each instance.

1. Docker image locally
2. Docker image on azure
3. Clean Wordpress (no docker) on azure

the error:

An error occurred while fetching file from: /wp-content/themes/Divi%20Child%20Theme//import/content.xml!
Reason: http_request_failed - A valid URL was not provided..

![AuthSiteErrorDataImport](https://user-images.githubusercontent.com/52284584/87236040-c2457a80-c398-11ea-8777-24b5d6779625.PNG)

seems like there might be a double slash after the Theme name and import directory.  Not sure.

Thanks

Antonio

**Comment by stevendaar** [comment]
i also am having a few issues:

(a) i don't see how or where to access the "[SaaS Academy] Authority Site - Theme Instructions.pdf" file

(b) i've installed themes onto WP before so figured i could go without needing instructions but when i tried i got this error:

![Screen Shot 2020-07-11 at 10 51 14 PM](https://user-images.githubusercontent.com/68175362/87238544-46aff180-c3c9-11ea-9719-59ec178766e0.png)

below are the contents of what i downloaded from this Github page....unsure if i need to install the Divi Child Theme first or how to do that because it's a Folder instead of a Zip File and then the Zip file with the 'SaaS Academy Theme' gave me the error in the first screenshot above when trying to install it

<img width="769" alt="Screen Shot 2020-07-11 at 10 58 15 PM" src="https://user-images.githubusercontent.com/68175362/87238600-2fbdcf00-c3ca-11ea-9c8d-4ec40b11626b.png">

edit to note that the README.md file that that came in the download just repeats what is said on the Github page without any further info on how to access the "[SaaS Academy] Authority Site - Theme Instructions.pdf" file

**Comment by fitprotracker** [comment]
@stevendaar 

you just need to extract the Saas Academy Wordpress Theme.zip file.  Inside there you will see the pdf and the two zip files.

**Comment by stevendaar** [comment]
thanks @fitprotracker - - that worked for me. much appreciated 

i was able to successfully use the Importing Demo Data function on the site i was testing this on: http://stevedaar.com/ 

sorry i don't have anything more useful for you to get past that step

if you haven't yet, possibly email Dan's support team about this if you're still stuck

**Comment by Vivekananthan** [comment]
@fitprotracker I feel that this error: "An error occurred while fetching file from: /wp-content/themes/Divi%20Child%20Theme//import/content.xml!
Reason: http_request_failed - A valid URL was not provided..

Tells me that the Site URL or WordPress URL is not properly setup. 

If you go to Settings -> General, please make sure the site address is setup properly. 

I happen to test it out on a fresh [installation](https://dmsapwp.wpengine.com/) today, so my site url and wordpress url looks like this -> https://share.getcloudapp.com/Qwulgr5r

Please let me know if that solves the issue? 

Thanks,
Vive

**Comment by Vivekananthan** [comment]
@fitprotracker Is this still an issue? Thanks

**Comment by fitprotracker** [comment]
sorry, i think i got around my editing something in PHP, but cant remember.
